namespace FFmpegWinUI
{
    [default_interface]
    runtimeclass ProgressEventArgs
    {
        ProgressEventArgs();

        UInt64 ReceivedBytes;
        UInt64 TotalBytes;
        Double Percentage;
        Double Speed;
    }

    [default_interface]
    runtimeclass FFmpegService
    {
        FFmpegService();
        FFmpegService(Windows.System.DispatcherQueue dispatcher);
        Windows.Foundation.IAsyncAction StartDownloadAsync(String url, String fileName);
        //进度条事件
        event Windows.Foundation.EventHandler<FFmpegWinUI.ProgressEventArgs> ProgressChanged;
        event Windows.Foundation.EventHandler<String> StatusChanged;
    }
}

